### ISSUE TITLE
openai 使用有报错

### ISSUE THREAD

**Issue by cyshooter** [Ding-Kyoma/EasyTrans-mac#12]
使用open ai时，有以下报错信息：
Traceback (most recent call last):
  File "C:\workspace\env\easytrans\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\trans\EasyTrans-mac\translate_func.py", line 170, in translate
    completion = openai.ChatCompletion.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\env\easytrans\Lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by Ding-Kyoma** [comment]
暂时用openai==0.28解决。等之后更新代码适配 openai>1.0.0
