### ISSUE TITLE
翻译报错，输出空白内容，JSONDecodeError

### ISSUE THREAD

**Issue by Rock3Yu** [Ding-Kyoma/EasyTrans-mac#14]
电脑：MacBook pro m3
系统：macOs 14
环境：conda（新建了环境，按照教程走的，也安装了两个arm架构的两行指令）
翻译api：有道，更改了account.py and main.py
结果：output文件夹，输出了空白的几个文件

报错内容：
```
python main.py
当前翻译的pdf名字 2201.01416.pdf
                                                                                          
==================================== 正在翻译第1页 ====================================
Latent Vector Expansion using Autoencoder for Anomaly Detection                           
2201.01416.pdf:   0%|                                               | 0/3 [00:00<?, ?it/s]
翻译过程出现异常......
Traceback (most recent call last):
  File "/Users/xxx/Downloads/tmp/EasyTrans-mac/main.py", line 234, in main
    res = net_translate(trans_pragraph).replace(' ', '')
  File "/Users/xxx/Downloads/tmp/EasyTrans-mac/translate_func.py", line 109, in youdao_translate
    ta = json.loads(html)
  File "/Users/xxx/anaconda3/envs/trans/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/anaconda3/envs/trans/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/anaconda3/envs/trans/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/Users/xxx/Downloads/tmp/EasyTrans-mac/output_file/2201.01416_translated.pdf
Total translation time: 0.160043 sec
 
保存txt成功
保存txt成功
保存docx成功
保存pdf成功

Total translation time: 0.2 sec
```

请问这个是什么问题？感谢解答，祝周末愉快。

**Comment by Ding-Kyoma** [comment]
有道api不维护了，请使用百度翻译/chatgpt
