### ISSUE TITLE
[WinError 32]

### ISSUE THREAD

**Issue by ffaffAHA** [Ding-Kyoma/EasyTrans-mac#19]
## windows端，使用的是VScode的python3.10虚拟环境。报错如下

```
Finite element analysis o...:  42%|████████████████████▍                            | 5/12 [01:06<01:32, 13.25s/it] 
翻译过程出现异常......
Traceback (most recent call last):
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connection.py", line 196, in _new_conn     
    sock = connection.create_connection(
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen   
    response = self._make_request(
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connection.py", line 398, in request       
    self.endheaders()
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\http\client.py", line 976, in send
    self.connect()
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connection.py", line 236, in connect       
    self.sock = self._new_conn()
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connection.py", line 205, in _new_conn     
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x000001FFFF42A110>, 'Connection to api.fanyi.baidu.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen   
    retries = retries.increment(
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\urllib3\util\retry.py", line 519, in increment     
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.fanyi.baidu.com', port=80): Max retries exceeded with url: /api/trans/vip/translate?q=3000+&from=en&to=zh&appid=20240601002066899&salt=37368&sign=30c31c1d4cf63e45ad08561a34f0f0a8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FFFF42A110>, 'Connection to api.fanyi.baidu.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\TranslationPDF\EasyTrans-mac\main.py", line 234, in main
    res = net_translate(trans_pragraph).replace(' ', '')
  File "e:\TranslationPDF\EasyTrans-mac\translate_func.py", line 40, in __call__
    return self.func(*args, **kwargs)
  File "e:\TranslationPDF\EasyTrans-mac\translate_func.py", line 254, in baidu_translate
    j = requests.post('http://api.fanyi.baidu.com/api/trans/vip/translate', params=head, headers=headers)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\sessions.py", line 589, in request        
    resp = self.send(prep, **send_kwargs)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\TranslationPDF\EasyTrans-mac\.conda\lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='api.fanyi.baidu.com', port=80): Max retries exceeded with url: /api/trans/vip/translate?q=3000+&from=en&to=zh&appid=20240601002066899&salt=37368&sign=30c31c1d4cf63e45ad08561a34f0f0a8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FFFF42A110>, 'Connection to api.fanyi.baidu.com timed out. (connect timeout=None)'))
E:\TranslationPDF\EasyTrans-mac\output_file\Finite element analysis of temperature distribution in single metallic powder layer during metal laser sintering_translated.pdf
Total translation time: 66.7643 sec

Reason: 'gbk' codec can't encode character '\ufffd' in position 214: illegal multibyte sequence
保存txt异常
Reason: 'gbk' codec can't encode character '\ufffd' in position 214: illegal multibyte sequence
保存txt异常
保存docx成功
保存pdf成功

Reason: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'E:\\TranslationPDF/EasyTrans-mac/input_file/Finite element analysis of temperature distribution in single metallic powder layer during metal laser sintering.pdf'      
转移原始文件失败，可能是文件在另外的软件打开。
请手动将pdf文件移出input文件夹。
Total translation time: 67.2 sec
```

**Comment by ffaffAHA** [comment]
问题解决了，后台不知道挂什么软件了，vpn？
